### PR TITLE
update: remove prepopulated queries

### PR DESCRIPTION
**Pull request by olekkorob**
- #604

### CODE REVIEW

**Comment by flaneuse** [comment]
@olekkorob you'll need to also merge in the changes from the [compare-lineage-no-preload branch](https://github.com/outbreak-info/outbreak.info/tree/compare-lineage-no-preload) branch in order to get goals #1-3 working as well (to not load any data by default, but only execute the API calls upon request).

it'd be good for you to also test out that the code i wrote does what we want and doesn't introduce any other issues. thanks!

**Comment by olekkorob** [comment]
> @olekkorob you'll need to also merge in the changes from the [compare-lineage-no-preload branch](https://github.com/outbreak-info/outbreak.info/tree/compare-lineage-no-preload) branch in order to get goals #1-3 working as well (to not load any data by default, but only execute the API calls upon request).
> 
> it'd be good for you to also test out that the code i wrote does what we want and doesn't introduce any other issues. thanks!

Okay, got it. Thank you

**Comment by flaneuse** [comment]
This looks good.  Can you make another few changes?  Basically, I want to have boxes 1-5 add to the "Already selected lineages" area, forcing the user to select which options they want, then click "create report", rather than having a selected option already change the route and execute the query (to hopefully save on time...).

1. In **box 2**, when you select something from the dropdown menu:
   a. Remove the "Add XXX Lineages" button.
   b. Add the selected item to the "Already selected lineages". Do not change the route or execute the route/query till the user presses "create report"
2. In **box 3**, similarly don't execute the call when a user selects a lineage -- just add it to the "Already selected lineages" area.
3. In **box 4**:
   a. Create a new button (or change one of the existing ones) that says "Lookup XXX-containing lineages" ("Lookup S:E484K-containing lineages").  It should have a plus sign next to it.
   b. On click: have that button do the API call which looks up the lineages which contain that mutation (should be the call within `addMutations` to `getComparisonByMutations`). Add those lineages to `this.selectedPango` so they show up in "Already selected lineages". Do not change the route or execute the route/query till the user presses "create report" 
  c. Remove the existing "Add XXX-containing lineages" and "Clear and add XXX-containing lineages" buttons
5. In **box 5**: similar changes to box 4.
   a. Create a new button (or change one of the existing ones) that says "Lookup lineages in XXX" ("Lookup lineages in Ukraine").  It should have a plus sign next to it.
   b. On click: have that button do the API call which looks up the lineages found in the location over the last 60 days. Add those lineages to `this.selectedPango` so they show up in "Already selected lineages". Do not change the route or execute the route/query till the user presses "create report" 
  c. Remove the existing "Add lineages in XXX" and "Clear and add lineages in XXX" buttons
  6. adjust the `checkPango` function to only display the warning if `selectedPango` includes `"Omicron"`, `"BA.1"`, or anything that starts with `BA.1` (e.g. `BA.1.1.18`, `BA.1.23`, etc.). -- sorry, that was my fault
    a. Also collapse the conditional for the warning to only rely on the `checkPango` function (lines 795-803).  Seems cleaner to only run the conditional through that function.

Lmk if you have any questions. Thanks!

**Comment by olekkorob** [comment]
Hi, @flaneuse , Thank you for your detailed explanation for requirements.
They are mostly clear for me and I have already done from 1-4.
But in 5, what does mean collapse the conditional for the warning?

**Comment by flaneuse** [comment]
@olekkorob : for 5a, I meant this conditional:

```
          v-if="
                  geneData.key === 'S' &&
                  selectedPango &&
                  (selectedPango.includes('Omicron') ||
                    selectedPango.includes('omicron') ||
                    selectedPango.includes('B.1.1.529') ||
                    checkPango)
                "
```

could be replaced by a single call, which incorporates the `geneData.key=="S"` and `selectedPango.includes("Omicron")` checks:

`v-if="checkPango"`

**Comment by flaneuse** [comment]
@olekkorob a couple of small changes:

1. Once the user clicks `CREATE REPORT` button, let's close the `change lineages` expansion panel (`data-target="#select-lineages"`)

3. In box 4, let's remove the calls to `/lineage-mutations?pangolin_lineage=X&frequency=0` on the "lookup X-containing lineages".  For instance:

- If you type S:N211I:
Screenshot 2023-01-26 at 5 36 34 PM

- clicking "Lookup S:N211I-containing lineages" will trigger a call to https://api.outbreak.info/genomics/mutations-by-lineage?mutations=S:N211I&frequency=0.9. All of the `pangolin_lineage` from the result of that call should be added to `this.selectedPango` and de-duplicated.  And then stop here!  For this example, that should add 27 pills to the "Already selected lineages"
Screenshot 2023-01-26 at 5 36 12 PM

- Currently, that will trigger 27x API calls: https://api.outbreak.info/genomics/lineage-mutations?pangolin_lineage={pangolin_lineage}&frequency=0, which is what we don't want (yet).  We want to wait and only execute them after the user selects the "Create Report" button.

3. Same thing for Box 5 -- only make the call to https://api.outbreak.info/genomics/prevalence-by-location-all-lineages?location_id={location}&other_threshold=0.03&nday_threshold=5&ndays=60&window=60&ndays=60&cumulative=true and add the `pangolin_lineage` from the result, but don't execute the calls to `/lineage-mutations` till after the user clicks the "Create Report" button

**Comment by flaneuse** [comment]
I was playing around with changing the call to fetch all the mutations for each lineage. There are two options for fetching all the calls to `lineage-mutations`:
1. Run a forkJoin over all the queries and loop over each `pangolin_lineage` to fetch results and merge together(currently what's running on the main branch).
2. Combine all the `pangolin_lineages` into a single comma-separated query for the backend, taking advantage of the looping built into the API endpoint.

Neither option is perfect.

The second option is faster for an individual query. However, especially for VOCs which are expanded into a series of `lineage OR lineage` queries, you quickly run into URI too long errors. Also, if you sequentially add lineages, you can't take advantage of NGINX caching, since each addition changes the API request.

In addition to the speed issue with the first method, though, the other issue is that if you request data for a lot of lineages, you run into throttling/429 errors, because you're requesting more data.

We might want to alert the user they've selected too many lineages and/or add a pause between groups of queries if they've selected too many.

We should also revisit this when:
* we have a more robust way of querying lineages and sublineages.  
* the lineages-mutations endpoint is optimized to be faster.

If it's fast and the queries have fewer characters, we'll probably want to move back to using the API to execute one query instead of a `forkJoin` loop of queries.

**Pull request merged**
